services:
  db:
    image: postgres:16
    container_name: urlshortener-db
    environment:
      POSTGRES_DB: UrlShortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - urlshortener_pgdata:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d UrlShortener" ]
        interval: 5s
        timeout: 3s
        retries: 20 
      
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: urlshortener-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Shortener__BaseUrl: http://localhost:8080
      ConnectionStrings__ManagerDbCS: Host=db;Port=5432;Database=UrlShortener;Username=postgres;Password=postgres
    ports:
        - "8080:8080"
          
volumes:
    urlshortener_pgdata: